In [1]:
# --- standard library imports ---
import numpy as np
import pandas as pd
from pathlib import Path

from ase import Atoms
from ase.io import read, Trajectory
from ase.visualize import view
from pymatgen.io.ase import AseAtomsAdaptor

# --- IMPORTS FROM THIS PROJECT ---
from gnome_dreams_oer_screening import OER_catalyst_study
from gnome_dreams_oer_screening import RelationalFrame 
from gnome_dreams_oer_screening import Explog
from gnome_dreams_oer_screening.vasp.job_handler import Job_handler

In [2]:
EXPLOG = Explog('TEMP_vasp_calcs', 'test')

In [3]:
# Test structures, to hand to the study object:
ZrO2_m = read('ZrO2_m.cif')
TiO2_r = read('TiO2_rutile.cif')
test_cands = Trajectory('test_cands.traj')

atoms = test_cands[18]
S = AseAtomsAdaptor.get_structure(atoms)

In [4]:
# Dummy setup of frist row (for testing):
study = OER_catalyst_study(atoms)
cant_id = "07286qnfd"

EXPLOG.add_candidate(
    candidate_id=cant_id,
    reason_or_hypothesis="Ir sites should be great", 
    notes="this is a great candidate", 
    study_obj=study
)

EXPLOG.relational_frame.candidates.df

,candidate_id,reason_or_hypothesis,notes,study_obj,OHDone,idealOverPotential
0,07286qnfd,Ir sites should be great,this is a great candidate,<gnome_dreams_oer_screening.oer.oer_study.OER_...,<NA>,<NA>

In [ ]:
EXPLOG.add_process(candidate_id=cant_id, 
                   calculation_type="bulk_relaxation")
EXPLOG.relational_frame.processes.df

,process_id,candidate_id,job_type,slurmID,status,termination_index,site_index,VASP_dir,processNote
0,0,07286qnfd,bulk_relaxation,<NA>,un-submitted,None,None,TEMP_vasp_calcs\20260209_235954__07286qnfd_bul...,None

In [8]:
EXPLOG.submit_process(candidate_id=cant_id, process_id=str(0))
EXPLOG.relational_frame.processes.df

RuntimeError: Process 0, is not an un-submitted process and cannot be submitted.

In [7]:
EXPLOG.relational_frame.processes.df

,process_id,candidate_id,job_type,slurmID,status,termination_index,site_index,VASP_dir,processNote
0,0,07286qnfd,bulk_relaxation,<NA>,submitted,None,None,TEMP_vasp_calcs\20260209_235954__07286qnfd_bul...,None

In [ ]:
df = EXPLOG.relational_frame.processes.df
df[(df.job_type == 'bulk_relaxation') &
   (df.termination_index.isna()) 
#    (df.site_index == None)
   ]

,process_id,candidate_id,job_type,slurmID,status,termination_index,site_index,VASP_dir,processNote
0,10,07286qnfd,bulk_relaxation,<NA>,un-submitted,None,None,TEMP_vasp_calcs\20260209_225814__07286qnfd_bul...,None
1,11,07286qnfd,bulk_relaxation,<NA>,un-submitted,None,None,TEMP_vasp_calcs\20260209_225814__07286qnfd_bul...,None

In [ ]:
JOB_HANDLER.submit_vasp_calculation(
    candidate_id = cant_id, process_id = str(10), resource = 'xeon24el8'
    )

EXPLOG.processes.df

,process_id,candidate_id,job_type,slurmID,status,VASP_dir,processNote
0,10,07286qnfd,bulk_relaxation,<NA>,submitted,TEMP\vasp_calculations\07286qnfd_bulk_relaxati...,<NA>

In [ ]:
cant_id = "sdaf32rdf"
EXPLOG.candidates.add_row(
    {"candidate_id": cant_id,
     "reason_or_hypothesis": "Ir sites should be great", 
     "notes": "this is a great candidate", 
     "study_obj": study},
     allow_update=True,
)
JOB_HANDLER.enter_in_log(
    candidate_id = cant_id,
    calculation_type = "bulk_relaxation"
)

In [ ]:
JOB_HANDLER.update_log().df

,process_id,candidate_id,job_type,slurmID,status,VASP_dir,processNote
0,10,07286qnfd,bulk_relaxation,<NA>,submitted,TEMP\vasp_calculations\07286qnfd_bulk_relaxati...,<NA>
1,20,sdaf32rdf,bulk_relaxation,<NA>,un-submitted,TEMP\vasp_calculations\sdaf32rdf_bulk_relaxati...,<NA>